#!/usr/bin/env python3
"""Create the `samples/` fixtures used by the GPU smoke gates.

Everything is synthetic and therefore CC0 by construction: three images with
distinct palettes, subjects and compositions, and one 10 s clip with three
hard cuts (so shot detection has something to find). The clip is encoded
with the ffmpeg binary that `imageio-ffmpeg` already ships in the backend
env; nothing new is added to the repository.

    cd backend && uv run python ../scripts/make-samples.py
"""

from __future__ import annotations

import math
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SAMPLES = ROOT / "samples"


def _gradient(size: tuple[int, int], top: tuple[int, int, int], bottom: tuple[int, int, int]) -> Image.Image:
    width, height = size
    image = Image.new("RGB", size)
    pixels = image.load()
    assert pixels is not None
    for y in range(height):
        t = y / max(1, height - 1)
        color = tuple(int(top[i] * (1 - t) + bottom[i] * t) for i in range(3))
        for x in range(width):
            pixels[x, y] = color
    return image


def ref_01() -> Image.Image:
    """Warm interior: a figure silhouette centre-left, a window top-right."""
    image = _gradient((1280, 720), (60, 40, 30), (20, 15, 12))
    draw = ImageDraw.Draw(image)
    draw.rectangle((900, 80, 1180, 360), fill=(230, 190, 120))
    draw.ellipse((380, 180, 520, 320), fill=(210, 170, 130))
    draw.rectangle((350, 320, 550, 700), fill=(90, 60, 45))
    draw.rectangle((0, 600, 1280, 720), fill=(35, 25, 20))
    return image


def ref_02() -> Image.Image:
    """Cold exterior: a ridge line, a small figure, a big sky."""
    image = _gradient((1280, 720), (120, 150, 190), (220, 230, 240))
    draw = ImageDraw.Draw(image)
    points = [(0, 520)] + [(x, 520 - int(90 * math.sin(x / 140.0)) - x // 12) for x in range(0, 1281, 40)] + [(1280, 720), (0, 720)]
    draw.polygon(points, fill=(240, 244, 248))
    draw.rectangle((640, 430, 660, 480), fill=(40, 40, 48))
    draw.ellipse((638, 412, 662, 436), fill=(40, 40, 48))
    return image


def ref_03() -> Image.Image:
    """Graphic/vector-like: flat colours, hard edges, a centred prop."""
    image = Image.new("RGB", (1024, 1024), (245, 240, 230))
    draw = ImageDraw.Draw(image)
    draw.rectangle((112, 112, 912, 912), fill=(30, 120, 110))
    draw.ellipse((312, 312, 712, 712), fill=(240, 90, 60))
    draw.rectangle((472, 200, 552, 824), fill=(250, 220, 70))
    return image


def make_clip(target: Path, seconds: int = 10, fps: int = 24) -> bool:
    try:
        import imageio_ffmpeg  # type: ignore[import-not-found]

        ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
    except Exception as exc:  # noqa: BLE001
        print(f"imageio-ffmpeg unavailable ({exc}); skipping the clip", file=sys.stderr)
        return False
    with tempfile.TemporaryDirectory() as tmp:
        frames_dir = Path(tmp)
        shots = [ref_01(), ref_02(), ref_03().resize((1280, 720))]
        total = seconds * fps
        for index in range(total):
            shot = shots[min(len(shots) - 1, index * len(shots) // total)]
            frame = shot.copy()
            draw = ImageDraw.Draw(frame)
            # A moving marker so consecutive frames differ (optical flow has motion to measure).
            x = 40 + int((index % (total // len(shots))) * 3)
            draw.rectangle((x, 660, x + 60, 700), fill=(255, 255, 255))
            frame.save(frames_dir / f"f{index:04d}.png")
        command = [ffmpeg, "-y", "-loglevel", "error", "-framerate", str(fps), "-i", str(frames_dir / "f%04d.png"), "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "veryfast", str(target)]
        subprocess.run(command, check=True)
    return True


def main() -> None:
    SAMPLES.mkdir(exist_ok=True)
    for name, maker in (("ref-01.jpg", ref_01), ("ref-02.jpg", ref_02), ("ref-03.png", ref_03)):
        path = SAMPLES / name
        if not path.exists():
            maker().save(path, quality=92)
            print(f"wrote {path.relative_to(ROOT)}")
    clip = SAMPLES / "clip-01.mp4"
    if not clip.exists() and make_clip(clip):
        print(f"wrote {clip.relative_to(ROOT)}")
    readme = SAMPLES / "README.md"
    if not readme.exists():
        readme.write_text(
            "# samples\n\nSynthetic fixtures for the GPU smoke gates (see docs/RTX_4070_TEST_MATRIX.md).\n"
            "Generated by `scripts/make-samples.py`; CC0 — no third-party content.\n\n"
            "- `ref-01.jpg` warm interior, one figure, window light\n- `ref-02.jpg` cold exterior, ridge, small figure\n"
            "- `ref-03.png` flat graphic, centred prop\n- `clip-01.mp4` 10 s, 24 fps, three hard cuts, a moving marker\n",
            encoding="utf-8",
        )
    if shutil.which("git"):
        print("samples ready")


if __name__ == "__main__":
    main()
